package panels

import (
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/MHBehzadian/nexra-mirzabot/internal/db"
	"github.com/MHBehzadian/nexra-mirzabot/internal/php"
)

func randHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// --- cookie jar text, compatible with what curl's CURLOPT_COOKIEJAR wrote
// into datelogin.access_token, so either bot version can reuse the session.

func cookieJarText(host string, cookies []*http.Cookie) string {
	var b strings.Builder
	b.WriteString("# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n")
	for _, c := range cookies {
		dom := host
		if c.HttpOnly {
			dom = "#HttpOnly_" + dom
		}
		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}
		exp := int64(0)
		if !c.Expires.IsZero() {
			exp = c.Expires.Unix()
		}
		path := c.Path
		if path == "" {
			path = "/"
		}
		b.WriteString(strings.Join([]string{dom, "FALSE", path, secure, strconv.FormatInt(exp, 10), c.Name, c.Value}, "\t") + "\n")
	}
	return b.String()
}

func cookieHeader(jar string) string {
	var parts []string
	for _, line := range strings.Split(jar, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.HasPrefix(line, "#HttpOnly_") {
			line = strings.TrimPrefix(line, "#HttpOnly_")
		} else if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		f := strings.Split(line, "\t")
		if len(f) >= 7 {
			parts = append(parts, f[5]+"="+f[6])
		}
	}
	return strings.Join(parts, "; ")
}

func hostOf(u string) string {
	s := u
	if i := strings.Index(s, "://"); i >= 0 {
		s = s[i+3:]
	}
	if i := strings.IndexAny(s, "/?#"); i >= 0 {
		s = s[:i]
	}
	if i := strings.LastIndex(s, ":"); i >= 0 && !strings.Contains(s[i:], "]") {
		s = s[:i]
	}
	return s
}

// XUILogin is login($code_panel,$verify): returns the cookie header to use
// and the decoded login reply (nil when the session came from the cache).
func (m *Manager) XUILogin(panel db.Row, verify bool) (string, map[string]any) {
	panel = m.panelByID(panel.S("id"))
	if verify && panel.S("datelogin") != "" {
		c := loginCache(panel)
		if _, ok := fresh(c, 3000); ok {
			jar, _ := c["access_token"].(string)
			return cookieHeader(jar), nil
		}
	}
	r := req{method: "POST", url: panel.S("url_panel") + "/login", follow: true, timeout: 4 * time.Second,
		body:        formBody("username", panel.S("username_panel"), "password", panel.S("password_panel")),
		contentType: "application/x-www-form-urlencoded"}.do()
	if r.err != nil {
		return "", map[string]any{"success": false, "errror": r.err.Error()}
	}
	body := jsonObj(r.body)
	if body == nil {
		body = map[string]any{"success": false}
	}
	jar := cookieJarText(hostOf(panel.S("url_panel")), r.cookies)
	// Only a working session is worth caching for 50 minutes.
	if v, _ := body["success"].(bool); v {
		m.DB.Update("marzban_panel", "datelogin", string(marshal(map[string]any{"time": nowStamp(), "access_token": jar})), "id", panel.S("id"))
	}
	return cookieHeader(jar), body
}

func (m *Manager) xuiCall(panel db.Row, method, path string, payload []byte) []byte {
	cookie, _ := m.XUILogin(panel, true)
	ct := ""
	if payload != nil {
		ct = "application/json"
	}
	return req{method: method, url: panel.S("url_panel") + path, body: payload, contentType: ct, cookie: cookie,
		follow: true, insecure: true, headers: map[string]string{"Accept": "application/json"}, timeout: 15 * time.Second}.do().body
}

// XUIGetClient is get_Client(): the client traffic object or nil.
func (m *Manager) XUIGetClient(username string, panel db.Row) map[string]any {
	r := jsonObj(m.xuiCall(panel, "GET", "/panel/api/inbounds/getClientTraffics/"+username, nil))
	o, _ := r["obj"].(map[string]any)
	return o
}

func xuiClientSettings(clients []map[string]any, extra bool) string {
	cl := make([]any, len(clients))
	for i, c := range clients {
		cl[i] = c
	}
	s := map[string]any{"clients": cl}
	if extra {
		s["decryption"] = "none"
		s["fallbacks"] = []any{}
	}
	return string(marshal(s))
}

func (m *Manager) xuiAdd(panel db.Row, username string, expireMs int64, total float64, uuid, flow, subID string) map[string]any {
	cfg := map[string]any{
		"id": php.Intval(panel.S("inboundid")),
		"settings": xuiClientSettings([]map[string]any{{
			"id": uuid, "flow": flow, "email": username, "totalGB": jsonNumber(total), "expiryTime": expireMs,
			"enable": true, "tgId": "", "subId": subID, "reset": 0,
		}}, true),
	}
	return jsonObj(m.xuiCall(panel, "POST", "/panel/api/inbounds/addClient", marshal(cfg)))
}

// XUIUpdateClient is updateClient().
func (m *Manager) XUIUpdateClient(panel db.Row, cfg map[string]any, uuid string) map[string]any {
	return jsonObj(m.xuiCall(panel, "POST", "/panel/api/inbounds/updateClient/"+uuid, marshal(cfg)))
}

func (m *Manager) xuiCreate(panel db.Row, username string, expire int64, dataLimit float64) Out {
	subID := randHex(8)
	res := m.xuiAdd(panel, username, expire*1000, dataLimit, phpUUID(), "", subID)
	link := panel.S("linksubx") + "/" + subID + "#" + username
	config := DecodeIfBase64(OutputLink(link))
	if v, _ := res["success"].(bool); !v {
		return unsuccessful(res["msg"])
	}
	return Out{"status": "successful", "username": username, "subscription_url": link, "configs": []string{config}}
}

func (m *Manager) xuiData(panel db.Row, username string) Out {
	u := m.XUIGetClient(username, panel)
	if u == nil {
		return unsuccessful("User not found")
	}
	expire := num(u, "expiryTime") / 1000
	status := "disabled"
	if truthy(u["enable"]) {
		status = "active"
	}
	if php.Intval(str(u, "expiryTime")) != 0 && expire-float64(time.Now().Unix()) <= 0 {
		status = "expired"
	}
	link := panel.S("linksubx") + "/" + str(u, "subId") + "#" + username
	config := DecodeIfBase64(OutputLink(link))
	online := "offline"
	if lo := num(u, "lastOnline"); lo != 0 {
		if lo > 1e11 { // 3x-ui reports milliseconds
			lo /= 1000
		}
		online = php.Date("c", int64(lo))
	}
	return Out{
		"status": status, "username": u["email"], "data_limit": u["total"], "expire": expire,
		"online_at": online, "used_traffic": num(u, "up") + num(u, "down"), "links": []string{config}, "subscription_url": link,
	}
}

func (m *Manager) xuiRevoke(panel db.Row, username string) Out {
	c := m.XUIGetClient(username, panel)
	subID := randHex(8)
	link := panel.S("linksubx") + "/" + subID + "#" + username
	cfg := map[string]any{
		"id": php.Intval(panel.S("inboundid")),
		"settings": xuiClientSettings([]map[string]any{{
			"id": phpUUID(), "flow": "", "email": c["email"], "totalGB": c["total"], "expiryTime": c["expiryTime"],
			"enable": true, "subId": subID,
		}}, false),
	}
	m.XUIUpdateClient(panel, cfg, str(c, "uuid"))
	if c == nil {
		return unsuccessful("Unsuccessful")
	}
	return Out{"status": "successful", "configs": OutputLink(link), "subscription_url": link}
}

func (m *Manager) xuiModify(panel db.Row, username string, config map[string]any) Out {
	c := m.XUIGetClient(username, panel)
	base := map[string]any{
		"clients": []any{map[string]any{
			"id": c["uuid"], "flow": "", "email": c["email"], "totalGB": c["total"], "expiryTime": c["expiryTime"],
			"enable": true, "subId": c["subId"],
		}},
		"decryption": "none",
		"fallbacks":  []any{},
	}
	if s, ok := config["settings"].(string); ok {
		if patch := jsonObj([]byte(s)); patch != nil {
			base = replaceRecursive(base, patch).(map[string]any)
		}
	}
	cfg := map[string]any{"id": php.Intval(str(c, "inboundId")), "settings": string(marshal(base))}
	return Out(m.XUIUpdateClient(panel, cfg, str(c, "uuid")))
}

func (m *Manager) xuiReset(panel db.Row, username string) {
	c := m.XUIGetClient(username, panel)
	m.xuiCall(panel, "POST", "/panel/api/inbounds/"+str(c, "inboundId")+"/resetClientTraffic/"+username, []byte{})
}

func (m *Manager) xuiRemove(panel db.Row, username string) Out {
	cookie, _ := m.XUILogin(panel, true)
	r := jsonObj(req{method: "POST", url: panel.S("url_panel") + "/panel/api/inbounds/" + panel.S("inboundid") + "/delClientByEmail/" + username,
		cookie: cookie, follow: true, headers: map[string]string{"Accept": "application/json"}}.do().body)
	if v, _ := r["success"].(bool); !v {
		return unsuccessful(r["msg"])
	}
	return Out{"status": "successful", "username": username}
}

// replaceRecursive is array_replace_recursive for decoded JSON values.
func replaceRecursive(base, patch any) any {
	switch b := base.(type) {
	case map[string]any:
		p, ok := patch.(map[string]any)
		if !ok {
			return patch
		}
		out := map[string]any{}
		for k, v := range b {
			out[k] = v
		}
		for k, v := range p {
			if cur, ok := out[k]; ok {
				out[k] = replaceRecursive(cur, v)
			} else {
				out[k] = v
			}
		}
		return out
	case []any:
		p, ok := patch.([]any)
		if !ok {
			return patch
		}
		out := append([]any{}, b...)
		for i, v := range p {
			if i < len(out) {
				out[i] = replaceRecursive(out[i], v)
			} else {
				out = append(out, v)
			}
		}
		return out
	}
	return patch
}
